import {
  computePortfolioAnalytics,
  formatNprCompact,
  type PortfolioAnalyticsInput,
} from "@/lib/portfolioAnalytics";

function buildFallbackNarrative(input: PortfolioAnalyticsInput, analytics: ReturnType<typeof computePortfolioAnalytics>) {
  const tone =
    input.risk === "high"
      ? "This mix is tilted toward upside capture and will behave like a growth-first mandate."
      : input.risk === "moderate"
        ? "This mix stays balanced, pairing compounding potential with a reasonable shock absorber."
        : "This mix is built to preserve capital first, with growth added in measured doses.";

  return `${tone} Based on the submitted allocation, the portfolio is modeling an expected annual return of ${(analytics.expectedAnnualReturn * 100).toFixed(1)}% with estimated annual volatility near ${(analytics.expectedAnnualVolatility * 100).toFixed(1)}%. The current resilience score is ${analytics.resilienceScore}/100 and the liquidity profile is ${analytics.liquidityScore}/100, which means the structure is ${analytics.resilienceScore >= 70 ? "fairly durable under stress" : "still exposed to concentration or liquidity pressure"}.\n\nIf this portfolio compounds near the modeled rate, the projected value over ${input.horizonYears} years lands around ${formatNprCompact(analytics.projectedValue)}, including roughly ${formatNprCompact(analytics.monthlyContributionImpact)} generated by the monthly contribution schedule.`;
}

export async function POST(req: Request) {
  try {
    const input = (await req.json()) as PortfolioAnalyticsInput;
    const analytics = computePortfolioAnalytics(input);

    if (!input.aum || analytics.parsedAum <= 0) {
      return Response.json({ error: "A valid AUM is required." }, { status: 400 });
    }

    if (analytics.allocationTotal <= 0) {
      return Response.json({ error: "Allocation must be greater than zero." }, { status: 400 });
    }

    const prompt = `You are Blue Ocean Inco AI. Write exactly 2 short conversational paragraphs, with no markdown and no bullet points.

Use the following computed portfolio analytics exactly as the factual basis of your answer:
- AUM: ${formatNprCompact(analytics.parsedAum)}
- Risk profile: ${input.risk}
- Allocation mix: Equities ${input.equities}%, Fixed Income ${input.fixedIncome}%, Real Assets ${input.realAssets}%, Cash ${input.cash}%
- Expected annual return: ${(analytics.expectedAnnualReturn * 100).toFixed(2)}%
- Expected annual volatility: ${(analytics.expectedAnnualVolatility * 100).toFixed(2)}%
- Liquidity score: ${analytics.liquidityScore}/100
- Diversification score: ${analytics.diversificationScore}/100
- Resilience score: ${analytics.resilienceScore}/100
- Efficiency score: ${analytics.efficiencyScore}/100
- Investment horizon: ${input.horizonYears} years
- Projected portfolio value: ${formatNprCompact(analytics.projectedValue)}
- Contribution impact: ${formatNprCompact(analytics.monthlyContributionImpact)}

Requirements:
Paragraph 1 should explain what the numbers imply in practical portfolio terms.
Paragraph 2 should sound like a polished portfolio advisor speaking directly to the client, including one concrete improvement suggestion if the mix looks weak.
Do not mention any external AI provider or model.`;

    let commentary = buildFallbackNarrative(input, analytics);

    if (process.env.NVIDIA_API_KEY) {
      const response = await fetch("https://integrate.api.nvidia.com/v1/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${process.env.NVIDIA_API_KEY}`,
        },
        body: JSON.stringify({
          model: "meta/llama-3.1-8b-instruct",
          messages: [
            {
              role: "system",
              content:
                "You are Blue Ocean Inco AI, a premium investment analytics concierge. Never mention third-party models. No markdown.",
            },
            { role: "user", content: prompt },
          ],
          stream: false,
          max_tokens: 350,
          temperature: 0.4,
        }),
      });

      if (response.ok) {
        const data = await response.json();
        commentary = data.choices?.[0]?.message?.content?.trim() || commentary;
      } else {
        console.error("Portfolio analytics AI error:", response.status);
      }
    }

    return Response.json({
      analytics,
      commentary,
    });
  } catch (error) {
    console.error("Portfolio analytics route error:", error);
    return Response.json({ error: "Unable to process portfolio analytics." }, { status: 500 });
  }
}
